### ISSUE TITLE
Certora Report Master Issue

### ISSUE THREAD

**Issue by ControlCplusControlV** [delvtech/hyperdrive#391]
Master tracking issue for all the findings from [Certora's Report](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#file-qa-report-hyperdrive-md), PoC's and detailed explanations can be found at that doc

**Medium Issues**
- [x] #394

**Low Issues**
- [x] - [2.1. Benign re-entrancy in StethHyperdrive._deposit()](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#21-benign-re-entrancy-in-stethhyperdrive_deposit)
- [x] - [2.2. Flagging lack of Check-Effect-Interaction-Pattern involving state variables updates](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#22-flagging-lack-of-check-effect-interaction-pattern-involving-state-variables-updates)
- [x] - [2.3. Fees can be set to be greater than 100%](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#23-fees-can-be-set-to-be-greater-than-100)
 - [x] -[2.4. Consider using the existing SafeCast library's toUint128() and adding a toUint224() to prevent unexpected overflows when casting from various type int/uint values](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#24-consider-using-the-existing-safecast-librarys-touint128-and-adding-a-touint224-to-prevent-unexpected-overflows-when-casting-from-various-type-intuint-values)
- [x] - [2.5. Missing checks for address(0) when assigning values to address state variables](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#25-missing-checks-for-address0-when-assigning-values-to-address-state-variables)
 - [x] - [2.6. Return values of transfer()/transferFrom() not checked](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#26-return-values-of-transfertransferfrom-not-checked)
 
 **Informational Issues**
 - [x] -[3.1. Return values of approve() not checked](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#31-return-values-of-approve-not-checked)
 - [x] -[3.2. require() should be used instead of assert()](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#32-require-should-be-used-instead-of-assert)
 - [x] -[3.3. Use string.concat() or bytes.concat() instead of abi.encodePacked](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#33-use-stringconcat-or-bytesconcat-instead-of-abiencodepacked)
 > Cannot be done due to differences in type (not strictly all strings, or bytes, and for permit reference impls use `abi.encodePacked` so maintaining consistency there
 - [x] -[3.4. Contracts should have full test coverage](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#34-contracts-should-have-full-test-coverage)
 > WIP will be fixed later on but understood
 - [x] -[3.5. Consider using delete rather than assigning zero to clear values](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#35-consider-using-delete-rather-than-assigning-zero-to-clear-values)
 - [x] -[3.6. Function ordering does not follow the Solidity style guide](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#36-function-ordering-does-not-follow-the-solidity-style-guide)
 > Current order emphasizes readability based on the logical function of each contract, and helpers understand how each function is connected in a more clear way, deviating from the style guide with purpose.
 - [x] -[3.7. Change uint to uint256](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#37-change-uint-to-uint256)
 - [x] -[3.8. Lack of checks in setters](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#38-lack-of-checks-in-setters)
 - [x] -[3.9. type(uint256).max should be used instead of 2 ** 256 - 1](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#39-typeuint256max-should-be-used-instead-of-2--256---1)
 - [x] -[3.10. Missing Event for critical parameters change](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#310-missing-event-for-critical-parameters-change)
 - [x] -[3.11. Incomplete NatSpec: @return is missing on actually documented functions](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#311-incomplete-natspec-return-is-missing-on-actually-documented-functions)
 - [x] -[3.12. Use a modifier instead of a require/if statement for a special msg.sender actor](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#312-use-a-modifier-instead-of-a-requireif-statement-for-a-special-msgsender-actor)
 > While modifiers can be nice for readability when checking complex state, a modifier would just inline this check anyway, and personally this approach makes the conditions easier to read inside of the function, rather than in the function signature
 - [x] -[3.13. Constant state variables defined more than once](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#313-constant-state-variables-defined-more-than-once)
 > Main point of constants is to avoid magic numbers by giving them a name, relocating constants to other files would only further reduce readability within those files, negating a lot of the benefit in using a constant
 - [x] -[3.14. Consider using named mappings](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#314-consider-using-named-mappings)
 - [x] -[3.15. Adding a return statement when the function defines a named return variable, is redundant](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#315-adding-a-return-statement-when-the-function-defines-a-named-return-variable-is-redundant)
 > Readability is improved by this, and so we plan to leave it in to help when reading the code
 - [x] - [3.16. Take advantage of Custom Error's return value property](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#316-take-advantage-of-custom-errors-return-value-property)
 > Errors hint to where the error occurred within their description/type, and given the codesize issues indexing more values isn't neccessary for debugging, and would only increase codesize more
 - [x] -[3.17. "Unused Return"](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#317-unused-return)
 - [x] -[3.18. Contract does not follow the Solidity style guide's suggested layout ordering](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#318-contract-does-not-follow-the-solidity-style-guides-suggested-layout-ordering)
 > Current order emphasizes readability based on the logical function of each contract, and helpers understand how each function is connected in a more clear way, deviating from the style guide with purpose.
 - [x] -[3.19. Use Underscores for Number Literals (add an underscore every 3 digits)](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#319-use-underscores-for-number-literals-add-an-underscore-every-3-digits)
 - [x] -[3.20. Internal and private variables and functions names should begin with an underscore](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#320-internal-and-private-variables-and-functions-names-should-begin-with-an-underscore)
 > Internal variables are exposed by similar named functions in the dataProvider API, and other library functions benefit from  non underscore naming for clarity, rather than prefixes most of our functions
 - [x] -[3.21. Usage of floating pragma is not recommended](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#321-usage-of-floating-pragma-is-not-recommended)
 - [x] -[3.22. Variables need not be initialized to zero](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#322-variables-need-not-be-initialized-to-zero)
 > Clear initialization helps readability, and as Solidity 0.8 doesn't induce extra gas costs.
 - [x] -[3.23. The following unchecked statements are not documented](https://gist.github.com/DraveeCertora/bbd6dc84a88c2a5abf6b25a95f4f70fd#323-the-following-unchecked-statements-are-not-documented)
 > Code is taken from solmate, and documented as such, so it carries the audit with it, and can be assumed safe
